#ifndef REQUEST_OPTION_CODE_H_INCLUDED
#define REQUEST_OPTION_CODE_H_INCLUDED

#define SHUTDOWN 1000

#define REQUEST_FAILED -1

#define UNKNOWN_REQUEST_TYPE 16

#define INFO_BY_IP_AND_HOSTS 17
#define INFO_BY_IP_AND_HOSTS_PER_SUBNET 18
#define INFO_BY_IP_AND_SUBNETS 19

#define INFO_BY_HOSTS 20
#define INFO_BY_HOSTS_PER_SUBNET 21
#define INFO_BY_SUBNETS 22

#define SUBNETTING_BY_IP_AND_HOSTS 23
#define SUBNETTING_BY_IP_AND_HOSTS_PER_SUBNET 24
#define SUBNETTING_BY_IP_AND_SUBNETS 25

#define SUBNETTING_BY_HOSTS 26
#define SUBNETTING_BY_HOSTS_PER_SUBNET 27
#define SUBNETTING_BY_SUBNETS 28

extern int request_option_code(const char* request);

#endif

